# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e46494cde8c7c6ca7350ada80c364f35bd5a7dced1005d03ba3262fb96cb834c0c49fb8dc7dcc6fabaa713873ac032bfbeae326b07042f049ad60b5327a28f06

test:
  secret_key_base: 15baa4fa3443315c8cc1b530e84a5010a82ea27fd6ca109645aff892266680cb6b6edeb51978d341e794377a3566decd916fb108b59061c1d0e25abcd9267cf4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
